version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 5671:5671
      - 15672:15672
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
